{% set name = "flask-rest-jsonapi" %}
{% set version = "0.30.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/miLibris/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 39fd4c8e5eef85a37aab3337b09b9edc2ccfb1c1a7a97e4f2d5721a2acaa02a2

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - six
    - flask >=0.11
    - marshmallow ==2.18.0
    - marshmallow-jsonapi
    - sqlalchemy

test:
  imports:
    - flask_rest_jsonapi
    - flask_rest_jsonapi.data_layers
    - flask_rest_jsonapi.data_layers.filtering
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: http://github.com/miLibris/flask-rest-jsonapi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flask-REST-JSONAPI is a flask extension for building REST APIs'

  description: |
      Flask-REST-JSONAPI is a flask extension for building REST APIs. It combines the power of
      Flask-Restless and the flexibility of Flask-RESTful around a strong specification
      JSONAPI 1.0. This framework is designed to quickly build REST APIs and fit the
      complexity of real life projects with legacy data and multiple data storages
  doc_url: http://flask-rest-jsonapi.readthedocs.io/
  dev_url: http://github.com/miLibris/flask-rest-jsonapi

extra:
  recipe-maintainers:
    - sodre
