{% set name = "flask-rest-jsonapi" %}
{% set version = "0.19.0" %}
{% set sha256 = "ec3af1f556c5ed103232bfa8eee22e19d89d965f30b6ef5dc7cf7219349f83cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/miLibris/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - six
    - flask >=0.11
    - marshmallow 2.13.1
    - marshmallow-jsonapi
    - sqlalchemy

test:
  imports:
    - flask_rest_jsonapi
    - flask_rest_jsonapi.data_layers
    - flask_rest_jsonapi.data_layers.filtering

about:
  home: http://github.com/miLibris/flask-rest-jsonapi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flask-REST-JSONAPI is a flask extension for building REST APIs'

  description: |
      Flask-REST-JSONAPI is a flask extension for building REST APIs. It combines the power of
      Flask-Restless and the flexibility of Flask-RESTful around a strong specification
      JSONAPI 1.0. This framework is designed to quickly build REST APIs and fit the
      complexity of real life projects with legacy data and multiple data storages
  doc_url: http://flask-rest-jsonapi.readthedocs.io/
  dev_url: http://github.com/miLibris/flask-rest-jsonapi

extra:
  recipe-maintainers:
    - sodre
