appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YpsD9LyJTIuECi0Lenf6f2b3EgQPUZwj918PE83z2B/GyfBQNK913OBJojDsiixmbIHfApWdvgGAi11TgznoENpWxl0X28q0MNkj5y4Ud36mwOT+KciElnvBsEbGwe7ma4MdWKE8ODc7TkZlWASwWMSH+78trM5p24MyapXwVJqQ32a+XCtbPs2ciQYm3RA0G7imAz1shWLi5AjuKXkQ5xyEf0EZ3me05Y+C2LMhV16+Hrv7u/b/PNmCpa3u2R9hjcoJpK7lrztibsr3IE1vO/KjASCpL741snG7VuV2iFNmpFF1g6Abm0PeMap8Y1GLlHrbsgLSraVSdlnS/aicMjoh0r8/BxowokUPCezJhplGfVsJMeTXhjMlfqykTyu/vZrUxI/YzS2QI5U/YqiM9J7SQ+lcPBx4326CW/lz4oXpu/R1kuoZbicPm+MPyYQOGrTo9mYeapsHI0j0AjzDPcY39ETFWYdVBN/EmgA2X5q6Twx6/3fMRMSHCZtxqhDJy53eiCj0iKpWFrRAdOWdrB86yr+UJpN9UkJ1l8ftMevqTEWChanVx/hR12SkZ8aRlScaLgX1odHGyDtTSgVWefIo7dr1GCetRaK13uq/wi1cmcmTu1KEl0YEO8e8Zz/F8As6wMQJT+cqdEJA3jtmujVv+hv4By2/J/LOdaofHwg=}
