travis:
  secure:
    BINSTAR_TOKEN: EVcpJ/SwV1TduxXkkhSMI+k2iK13n15e+5xzCI1Gz3qN9mfwZaO9Wpc46ksgQZSPIG8kM/DhhElREM4eI4ryDnBoh0FSQV3pbCBUJcFdCWvQl53g1CEzAHqX5i+fOEigOIs39llmGJqdFwXJMRZ4z6ZqgNEffprz72dZk3wt7Pd88HU1Q2xr3iD08Das1gT2R1xBwt6bdQfNgvGUwTwXTkIUChtqwGMKKRq7MoK1SkWBgqg+LuXSDPLmUyTblSFG0DdLOWtfHFlUtrlFgdpL/J2UqyBhIQgRJrFB2M7wmhXpaTdsxXuyjwQde6o+IUbUie4ywZPu+jzXmMk8dQcUB33hca2lZ+Ruq+lkDXSj1Ou2KlyQHStEBMmRLk3GeOl5uC7uhIWbBKZIE3ZxEE4QmkQ2Y2TtwZGieMRczynI/1rk5pyUiUjFnfKy0FeAvysYHPudPsuW9Reo+4nf3OvYpMpHRnYL0FP936Flo//SwleUFtCDkr/MK43WUwbBT+ygRSChSFFRW12JuFBKyo66byW2Do9QgiDwwC+76cHXjZQKqWMgNMk7WejzaCEVbJScwg83g/qmz0vd+hijj2XkjguFevDjNYRhxmkcv7DZV20b6xzkms6IdUUemihN4bvDtUpy8FZPvrEdBx4ICYIYPGc1fT5+nkD+Jd4J/tqeclk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
